# Generated by Django 4.2.4 on 2023-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/imagen_producto'),
        ),
    ]
